#!/bin/sh

export AUTO=NON
export CHRONON=10000
export HAUTEUR=60
export LARGEUR=90
export NB_PROIE=900
export NB_REQUINS=100
export CYCLE_REPRODUCTION_REQUIN=12
export CYCLE_REPRODUCTION_PROIE=4
export VISIBILITE_REQUIN=2
export VISIBILITE_PROIE=2
export VUE_ARRIERE_REQUIN=OUI
export VUE_ARRIERE_PROIE=OUI
export POINTS_DE_VIE_REQUIN=12
export POINTS_PAR_REPAS=1

./lancement_scenario.sh
